spring:
  application:
    name: LearnWebFlux
#  threads:
#    virtual:
#      enabled: true

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/learn_web_flux
    username: postgres
    password: 2003
    sql:
      init:
        mode: always
        schema-locations: classpath:schema.sql

  server:
    port: 8080
    netty:
    connection-timeout: 20s # Limits the duration allowed to establish the initial TCP socket connection
    idle-timeout: 60s # Closes the connection if no read or write operations occur for 60 seconds.



#   C:\Apache24\Apache24\bin\ab.exe -n 5000 -c 500 -s 300 http://localhost:8080/api/v1/benchmark/users/1
#   1. C:\Apache24\Apache24\bin\ab.exe :- This is the path to ApacheBench. ab.exe = Apache Benchmark tool
#   2. -n 5000 = number of total requests
#   3. -c 500 = concurrency
#   4. -s 300 = timeout in seconds. means ApacheBench can wait up to 300 seconds for socket operations.


#  Core Features of Spring WebFlux
#  Feature      Spring MVC (Blocking)             Spring WebFlux (Reactive)

#  Threading    Model One thread per request      Few threads + non-blocking
#  ProgrammingStyle Imperative                    Reactive + Declarative
#  Server       Tomcat, Jetty (Servlet)           Netty (default), Undertow
#  Best For     Simple CRUD apps                  High concurrency, streaming
#  Backpressure Not supported                     Built-in



#  Why Spring WebFlux?
#       -> Assigning one waiter to each guest coming into the hotel vs one waiter taking
#          request from all the guests as they come in.

#  ⚡ Virtual threads are like giving every guest their own hologram waiter,
#  which are cheap to make that having 10,000 of them is no longer a
#  problem. The event loop model says "one waiter serving everyone is
#  more efficient." Virtual threads say "just make waiters basically free."
#  Both solve the original staffing crisis, through opposite philosophies.